---
- name: create sentinel working directory
  file: 
    path={{ redis_sentinel_dir }}
    state=directory
    recurse=yes
    owner={{ redis_user }}
  tags: redis

- name: check if sentinel log file exists
  stat: 
    path={{ redis_sentinel_logfile }}
  register: sentinel_logfile_stat
  tags: redis

- name: ensure that sentinel log file exists and is writable by redis
  file: 
    path={{ redis_sentinel_logfile }}
    owner={{ redis_user }}
    group={{ redis_user }}
    mode=0600
    state=touch
  when: sentinel_logfile_stat.stat.exists == False and redis_sentinel_logfile != '""'
  tags: redis

- name: create sentinel config file
  template: 
    src=redis-sentinel.conf.j2
    dest=/etc/redis/sentinel.conf
    owner={{ redis_user }}
  notify: 
    - restart sentinel
  tags: redis

- name: copy supervisord config
  template:
    src=redis-sentinel-supervisord.conf.j2
    dest={{ supervisord_programs_dir }}/redis-sentinel-supervisord.conf
    mode=0644
  notify:
    - reread supervisord
  tags: redis

