---
# file: roles/common/tasks/main.yml

- name: apt install java 
  apt: 
    name=default-jdk
    state=present
    update-cache=yes
  tags: java
  when: ansible_os_family == "Debian"

- name: yum install java 
  yum: 
    name=java-{{ java_version }}-openjdk-devel
    state=present
  tags: java
  when: ansible_os_family == "RedHat"

- name: java system environment configuration
  copy:
    src=java.sh
    dest=/etc/profile.d/java.sh
    owner=0
    group=0
    mode=0755
  tags: java

- name: Set JAVA_HOME ansible fact
  set_fact:
    java_home=/usr/java/default
  tags: java

- name: Create Ansible facts.d directory
  file:
    state=directory
    dest=/etc/ansible/facts.d
    owner=0
    group=0
    mode=0755
  tags: java

- name: Install java facts
  template:
    src=facts.j2
    dest=/etc/ansible/facts.d/java.fact
    owner=0
    group=0
    mode=0644
  tags: java

- name: Re-read facts
  setup:
    filter=ansible_local
  tags: java
