---
# Update apt-cache and install the latest Miniconda
- hosts: all
  sudo: yes
  tasks:
    - name: Update apt cache
      apt: update-cache=yes
  roles:
    - miniconda

# Install kafka, zookeeper, redis
- include: kafka.yml
- include: zookeeper.yml
- include: redis.yml

# Restart Kafka because its finicky like that
- hosts: scdev
  sudo: yes
  tasks:
    - name: Restart kafka
      supervisorctl: name='kafka' state=restarted