---
- name: restart redis
  supervisorctl:
    name=redis
    state=restarted

- name: wait for redis port
  wait_for:
    port={{ redis_port }}
    state=started

- name: restart sentinel
  supervisorctl:
    name=redis-sentinel
    state=restarted

- name: wait for sentinel port
  wait_for:
    port={{ redis_sentinel_port }}
    state=started
